test_cases = {
    "1109_demo": {
        "data":
            b"Subject: MIME Parsing Ambiguity Test 1109\r\n"
            b"MIME-Version: 1.0\r\n"
            b"Content-Type: mu<ltipart/m>ixed; boundary=+++boundary_multipart-1_boundary+++\r\n"
            b"Content-ID: 1\r\n"
            b"\r\n"
            b"This is preamble text.\r\n"
            b"--+++boundary_multipart-1_boundary+++\r\n"
            b"Content-Type: text/plain\r\n"
            b"Content-ID: 2\r\n"
            b"Content-Disposition: attachment; filename=att_1\r\n"
            b"\r\n"
            b"X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*\r\n"
            b"--+++boundary_multipart-1_boundary+++\r\n"
        ,
    },
    "1349_demo": {
        "data":
            b"Subject: MIME Parsing Ambiguity Test 1349\r\n"
            b"MIME-Version: 1.0\r\n"
            b"Content-Type: multipart/mixed; boundary=+++boundary_multipart-1_boundary+++\r\n"
            b"Content-ID: 1\r\n"
            b"\r\n"
            b"This is preamble text.\r\n"
            b"--+++boundary_multipart-1_boundary+++\r\n"
            b"Content-Type: app/octet-stream\r\n"
            b"Content-ID: 2\r\n"
            b"Content-Disposition: attachment; filename=att_1\r\n"
            b"\r\n"
            b"Hi, this is a test message! Best wishes.\r\n"
            b"--+++boundary_multipart-1_boundary+++\r\n"
            b"Content-Type:Content-Typemultipart/mixed; boundary=+++boundary_multipart-2_boundary+++\r\n"
            b"Content-ID: 3\r\n"
            b"\r\n"
            b"--+++boundary_multipart-2_boundary+++\r\n"
            b"Content-Type: text/plain\r\n"
            b"Content-ID: 4\r\n"
            b"Content-Disposition: attachment; filename=att_2\r\n"
            b"\r\n"
            b"X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*\r\n"
            b"--+++boundary_multipart-2_boundary+++\r\n"
            b"Content-Type: app/octet-stream\r\n"
            b"Content-Transfer-Encoding: quoted-printable\r\n"
            b"Content-ID: 5\r\n"
            b"Content-Disposition: attachment; filename=att_3\r\n"
            b"\r\n"
            b"X5O=21P=25=40AP=5B4=5CPZX54=28P=5E=297CC=297=7D=24EICAR-STANDARD-ANTIVIRUS-=\r\n"
            b"TEST-FILE=21=24H=2BH=2A\r\n"
            b"--+++boundary_multipart-2_boundary+++--\r\n"
            b"--+++boundary_multipart-1_boundary+++--\r\n"
    },
    "abnormal_line_break_between_headers_demo": {
        "data":
            b"MIME-Version: 1.0\r\n"
            b"Subject: qp eicar test case with abnormal line break between headers\r\n"
            b"Content-Type: multipart/mixed; boundary=foo\r\n"
            b"\r\n"
            b"--foo\r\n"
            b"Content-type: text/plain\r\n"
            b"\r\n"
            b"Email with an attachment.\r\nThis is the main body text part.\r\n"
            b"--foo\r\n"
            b"Content-type: text/plain; name=qp_eicar_1\r\n"
            b"Content-Disposition: attachment; filename=qp_eicar1\r\n"
            b"Content-Transfer-Encoding: quoted-printable\r\n"
            b"\r\n"
            b"<This is qp_wannacry.>"
            b"--foo--\r\n"
        ,
        "description": b"Encode raw eicar.com with Quoted-printable. Abnormal line break between headers."
    },
    "1140_demo": {
        "data":
            b"Subject: MIME Parsing Ambiguity Test 1140\r\n"
            b"MIME-Version: 1.0\r\n"
            b"Content-Type: multipart/mixed; boundary=+++boundary_multipart-1_boundary+++\r\n"
            b"Content-ID: 1\r\n"
            b"\r\n"
            b"This is preamble text.\r\n"
            b"--+++boundary_multipart-1_boundary+++\r\n"
            b"Content-Type: application/octet-stream\r\n"
            b"Content-Transfer-Encoding: quoted-printable\r\n"
            b"Content-ID: 2\r\n"
            b"Content-Disposition: attachment; filename=att_1\r\n"
            b"\r\n"
            b'Z=B2=12=E7w=3DP/=C3H*X$=F44?=85=930=FA=CA=F9=60=1Aqky+P=826=8F\r\n'
            b"--+++boundary_multipart-1_boundary+++\r\n"
            b"Content-Type: application/octet-stream\r"
            b"Content-Transfer-Encoding: base64\r\n"
            b"Content-ID: 3\r\n"
            b"Content-Disposition: attachment; filename=att_2\r\n"
            b"\r\n"
            b"<This is b64_wannacry.>"
            b"--+++boundary_multipart-1_boundary+++--\r\n"
    },
    "b64_split_encoding_demo": {
        "data":
            b"MIME-Version: 1.0\r\n"
            b"Subject: b64_split_encoding_2\r\n"
            b"Content-Type: multipart/mixed; boundary=foo\r\n"
            b"\r\n"
            b"--foo\r\n"
            b"Content-type: text/plain\r\n"
            b"\r\n"
            b"Email with an attachment.\r\nThis is the main body text part.\r\n"
            b"--foo\r\n"
            b"Content-type: application/octet-stream; name=b64_eicar_2\r\n"
            b"Content-Disposition: attachment; filename=b64_eicar2\r\n"
            b"Content-Transfer-Encoding: base64\r\n"
            b"\r\n"
            b"WDU=TyE=UCU=QEE=UFs=NFw=UFo=WDU=NCg=UF4=KTc=Q0M=KTc=fSQ=RUk=Q0E=Ui0=\r\n"
            b"U1Q=QU4=REE=UkQ=LUE=TlQ=SVY=SVI=VVM=LVQ=RVM=VC0=Rkk=TEU=ISQ=SCs=SCo=\r\n"
            b"--foo--\r\n"
        ,
        "description": b"Encode raw eicar.com with Base 64. Employ split encoding."
    },
    "b64_wannacry_test": {
        "data":
            b"MIME-Version: 1.0\r\n"
            b"Subject: b64 wannacry test case\r\n"
            b"Content-Type: multipart/mixed; boundary=foo\r\n"
            b"\r\n"
            b"--foo\r\n"
            b"Content-type: text/plain\r\n"
            b"\r\n"
            b"Email with an attachment.\r\nThis is the main body text part.\r\n"
            b"--foo\r\n"
            b"Content-type: application/octet-stream; name=b64_wanna\r\n"
            b"Content-Disposition: attachment; filename=b64_wanna\r\n"
            #b"Content-Transfer-Encoding: base64\r\n"
            b"\r\n"
            b"<This is b64_wannacry.>"
            b"--foo--\r\n"
        ,
        "description": b"Encode raw eicar.com with Base 64. Use app/octet type header."
    },
    "bound_begin_blank_char_test": {
        "data":
            b"MIME-Version: 1.0\r\n"
            b"Subject: bound_begin_blank_char_2\r\n"
            b"Content-Type: multipart/mixed; boundary=    foo\r\n"
            b"\r\n"
            b"--foo\r\n"
            b"Content-type: text/plain\r\n"
            b"\r\n"
            b"Email with an attachment.\r\nThis is the main body text part.\r\n"
            b"--foo\r\n"
            b"Content-type: application/octet-stream; name=qp_eicar_2\r\n"
            b"Content-Disposition: attachment; filename=qp_eicar2\r\n"
            b"Content-Transfer-Encoding: quoted-printable\r\n"
            b"\r\n"
            b"X5O=21P=25=40AP=5B4=5CPZX54=28P=5E=297CC=297=7D=24EICAR-STANDARD-ANTIVIRUS-=\r\nTEST-FILE=21=24H=2BH=2A\r\n"
            b"--foo--\r\n"
        ,
        "description": b"blank char at the beginning of separating boundary"
    },
    "1954": {
        "data":
            b"Subject: MIME Parsing Ambiguity Test 1954\r\n"
            b"MIME-Version: 1.0\r\n"
            b"Content-Type: multipart/mixed; boundary=+++boundary_multipart-1_boundary+++\r\n"
            b"Content-ID: 1\r\n"
            b"\r\n"
            b"--+++boundary_multipart-1_boundary+++\r\n"
            b"Content-Type: text/plain\r\n"
            b"Content-Transfer-Encoding: base64\r\n"
            b"Content-ID: 2\r\n"
            b"Content-Disposition: attachment; filename=1954_att_1_b64_eicar\r\n"
            b"\rB\n"
            b"WDVPIVAlQEFQWzRcUFpYNTQoUF4pN0NDKTd9JEVJQ0FSLVNUQU5EQVJELUFOVElWSVJVUy1URVNU\r\n"
            b"LUZJTEUhJEgrSCo=\r\n"
            b"--+++boundary_multipart-1_boundary+++\r\n"
            b"Content-Type: text/plain\r\n"
            b"Content-ID: 3\r\n"
            b"Content-Disposition: attachment; filename=1954_att_2\r\n"
            b"\r\n"
            b"Hi, this is a test message! Best wishes.\r\n"
            b"--+++boundary_multipart-1_boundary+++--\r\n"
    },
    "boundary_test": {
        "data":
            b"MIME-Version: 1.0\r\n"
            b"Subject: qp eicar test case\r\n" 
            b"Content-Type: multipart/mixed;\r\n"
            b"boundary=foo\r\n" 
            b"\r\n"
            b"--foo\r\n"
            b"Content-type: text/plain\r\n"
            b"\r\n"
            b"Email with an attachment.\r\nThis is the main body text part.\r\n"
            b"--foo\r\n"
            b"Content-type: application/octet-stream; name=qp_eicar_2\r\n"
            b"Content-Disposition: attachment; filename=qp_eicar2\r\n"
            b"Content-Transfer-Encoding: quoted-printable\r\n"
            b"\r\n"
            b"X5O=21P=25=40AP=5B4=5CPZX54=28P=5E=297CC=297=7D=24EICAR-STANDARD-ANTIVIRUS-=\r\n"
            b"TEST-FILE=21=24H=2BH=2A\r\n"
            b"--foo--\r\n"
        ,
        "description": b"Encode raw eicar.com with Quoted-printable. Use app/octet type header."
    },
}